language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

env:
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5,<1.6"
  - DJANGO="django>=1.6,<1.7"
  - DJANGO="django>=1.7,<1.8"

matrix:
  exclude:
    - python: 2.6
      env: DJANGO="django>=1.7,<1.8"
  allow_failures:
    - python: 3.2
    - python: 3.3
    - python: 3.4

install:
  - pip install $DJANGO selenium coveralls

before_script:
  - "export DISPLAY=:99.0"
  - "export DJANGO_SELENIUM_TESTS=1"
  - "sh -e /etc/init.d/xvfb start"

script:
  - python -Wonce `which coverage` run `which django-admin.py` test admin_enhancer --settings=test_settings --pythonpath=`pwd` -v2

after_success:
  - coverage report -m
  - coveralls
